"""empty message

Revision ID: 7f8bbd7f76ad
Revises: 77e8dc213bed
Create Date: 2025-05-21 09:56:13.905707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '7f8bbd7f76ad'
down_revision: Union[str, None] = '77e8dc213bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    orderstatusenum = postgresql.ENUM('ORDERED', 'COMPLETED', 'CANCELLED', name='orderstatusenum')
    orderstatusenum.create(op.get_bind())

    # Добавляем колонку с типом enum
    op.add_column('orders', sa.Column('status', sa.Enum('ORDERED', 'COMPLETED', 'CANCELLED', name='orderstatusenum'), nullable=False, server_default='ORDERED'))

def downgrade():
    op.drop_column('orders', 'status')

    # Удаляем enum тип
    orderstatusenum = postgresql.ENUM('ORDERED', 'COMPLETED', 'CANCELLED', name='orderstatusenum')
    orderstatusenum.drop(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
