"""empty message

Revision ID: 92e338c9524f
Revises: 7ee777775f58
Create Date: 2025-05-08 14:58:03.147167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e338c9524f'
down_revision: Union[str, None] = '7ee777775f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Создаём таблицу comment_ratings
    op.create_table(
        'comment_ratings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'comment_id', name='unique_user_comment_rating')
    )
    op.create_index(op.f('ix_comment_ratings_id'), 'comment_ratings', ['id'], unique=False)

    # Добавляем колонку rating с временным nullable=True и server_default='0'
    op.add_column('comments', sa.Column('rating', sa.Integer(), nullable=True, server_default='0'))

    # Добавляем колонку parent_id
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))

    # Создаём внешний ключ для parent_id с именем
    op.create_foreign_key('comments_parent_id_fkey', 'comments', 'comments', ['parent_id'], ['id'])

    # Убираем server_default и делаем rating NOT NULL
    op.alter_column('comments', 'rating', nullable=False, server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_parent_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'rating')
    op.drop_index(op.f('ix_comment_ratings_id'), table_name='comment_ratings')
    op.drop_table('comment_ratings')
    # ### end Alembic commands ###
