"""empty message

Revision ID: be24d643ad7f
Revises: e125778dd632
Create Date: 2025-05-19 09:13:16.864502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be24d643ad7f'
down_revision: Union[str, None] = 'e125778dd632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_product_favorite', 'favorites', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_product_favorite', 'favorites', type_='unique')
    # ### end Alembic commands ###
