"""empty message

Revision ID: c7bd72117db7
Revises: be24d643ad7f
Create Date: 2025-05-19 12:12:42.551258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bd72117db7'
down_revision: Union[str, None] = 'be24d643ad7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'barcode')
    op.add_column('orders', sa.Column('barcode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'barcode')
    op.add_column('order_items', sa.Column('barcode', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
