"""добавлениепоставщика

Revision ID: d7527122214b
Revises: 7f8bbd7f76ad
Create Date: 2025-06-12 22:11:22.380561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7527122214b'
down_revision: Union[str, None] = '7f8bbd7f76ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'suppliers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'user_id')
    # ### end Alembic commands ###
